/*
  This file (c) Copyright 1998 - 2000 M.I.T.
  
  This file is part of the Galaxy Communicator system. It is licensed
  under the conditions described in the file LICENSE in the root 
  directory of the Galaxy Communicator system.
*/

GAL_TAG("BAD_ALARM_KEY",GAL_BAD_ALARM_KEY)
GAL_TAG("BAD_ALARM_LIST",GAL_BAD_ALARM_LIST)
GAL_TAG("BAD_FILENAME",GAL_BAD_FILENAME)
GAL_TAG("BAD_INCLUDED_FILE",GAL_BAD_INCLUDED_FILE)
GAL_TAG("BAD_KEYWORD_PAIR",GAL_BAD_KEYWORD_PAIR)
GAL_TAG("BAD_KV_LIST",GAL_BAD_KV_LIST)
GAL_TAG("BAD_LIST",GAL_BAD_LIST)
GAL_TAG("BAD_LOCATION",GAL_BAD_LOCATION)
GAL_TAG("BAD_PROGRAM_FILE",GAL_BAD_PROGRAM_FILE)
GAL_TAG("BAD_RULE_CONDITION",GAL_BAD_RULE_CONDITION)
GAL_TAG("ENCLOSE_IN_QUOTES",GAL_ENCLOSE_IN_QUOTES)
GAL_TAG("INVALID_OPERATION",GAL_INVALID_OPERATION)
GAL_TAG("NOT_FRAME",GAL_NOT_FRAME)
GAL_TAG("NOT_INT",GAL_NOT_INT)
GAL_TAG("NOT_STRING",GAL_NOT_STRING)
GAL_TAG("NOT_VALID_KEYWORD",GAL_NOT_VALID_KEYWORD)
GAL_TAG("NO_HUB",GAL_NO_HUB)
GAL_TAG("NO_PROGRAM",GAL_NO_PROGRAM)
GAL_TAG("NO_RULE",GAL_NO_RULE)
GAL_TAG("NO_SERVER",GAL_NO_SERVER)
GAL_TAG("NO_SERVERS",GAL_NO_SERVERS)
GAL_TAG("NO_SERVER_NAME",GAL_NO_SERVER_NAME)
GAL_TAG("BAD_SERVICE_TYPE_NAME",GAL_BAD_SERVICE_TYPE_NAME)
GAL_TAG("DUPLICATE_SERVICE_TYPE_NAME",GAL_DUPLICATE_SERVICE_TYPE_NAME)
GAL_TAG("NO_SERVER_FOR_OPERATION",GAL_NO_SERVER_FOR_OPERATION)
GAL_TAG("SET_SERVERS_FIRST",GAL_SET_SERVERS_FIRST)
GAL_TAG("TOO_MANY_CONDITIONS",GAL_TOO_MANY_CONDITIONS)
GAL_TAG("TOO_MANY_PROGRAMS",GAL_TOO_MANY_PROGRAMS)
GAL_TAG("TOO_MANY_MESSAGES",GAL_TOO_MANY_MESSAGES)
GAL_TAG("TOO_MANY_RULES",GAL_TOO_MANY_RULES)
GAL_TAG("TOO_MANY_SERVERS",GAL_TOO_MANY_SERVERS)
GAL_TAG("TOO_MANY_SERVICE_TYPES",GAL_TOO_MANY_SERVICE_TYPES)
GAL_TAG("NO_MESSAGE_NAME",GAL_NO_MESSAGE_NAME)
GAL_TAG("UNKNOWN_MODE",GAL_UNKNOWN_MODE)
GAL_TAG("BAD_PROVIDER_ID",GAL_BAD_PROVIDER_ID)
GAL_TAG("BAD_PROVIDER_NAME",GAL_BAD_PROVIDER_NAME)
