/*
  This file (c) Copyright 1999 - 2000 M.I.T.
  
  This file is part of the Galaxy Communicator system. It is licensed
  under the conditions described in the file LICENSE in the root 
  directory of the Galaxy Communicator system.
*/

GAL_TAG("ALLOCATION_FAILED",GAL_ALLOCATION_FAILED)
GAL_TAG("ALREADY_HAVE_KEY",GAL_ALREADY_HAVE_KEY)
GAL_TAG("ALREADY_HAVE_TEST",GAL_ALREADY_HAVE_TEST)
GAL_TAG("ALREADY_HAVE_VALUE",GAL_ALREADY_HAVE_VALUE)
GAL_TAG("BAD_RULE_GROUPING",GAL_BAD_RULE_GROUPING)
GAL_TAG("BAD_RULE_TERMINATION",GAL_BAD_RULE_TERMINATION)
GAL_TAG("BAD_TOKEN",GAL_BAD_TOKEN)
GAL_TAG("COMMENT_AFTER_ESCAPE",GAL_COMMENT_AFTER_ESCAPE)
GAL_TAG("INVALID_DCTL_TAG",GAL_INVALID_DCTL_TAG)
GAL_TAG("INVALID_DIALOGUE_FUNCTION",GAL_INVALID_DIALOGUE_FUNCTION)
GAL_TAG("INVALID_PROGRAM_TAG",GAL_INVALID_PROGRAM_TAG)
GAL_TAG("INVALID_RULE_TAG",GAL_INVALID_RULE_TAG)
GAL_TAG("INVALID_TEST_VALUE",GAL_INVALID_TEST_VALUE)
GAL_TAG("NO_FILE",GAL_NO_FILE)
GAL_TAG("NO_OPERATION",GAL_NO_OPERATION)
GAL_TAG("NO_TEST_KEY",GAL_NO_TEST_KEY)
GAL_TAG("NULL_TEST",GAL_NULL_TEST)
GAL_TAG("STOPPED_BEFORE_EOF",GAL_STOPPED_BEFORE_EOF)
GAL_TAG("TOO_MANY_TOKENS",GAL_TOO_MANY_TOKENS)
GAL_TAG("UNKNOWN_PROGRAM_TAG",GAL_UNKNOWN_PROGRAM_TAG)
GAL_TAG("MISSING_CONSTITUENT",GAL_MISSING_CONSTITUENT)
GAL_TAG("DOUBLE_NEGATIVE",GAL_DOUBLE_NEGATIVE)
